apiVersion: v1
kind: Secret
metadata:
  name: stock-ticker-secrets
  labels:
    {{- include "stock-ticker.labels" . | nindent 4 }}
type: Opaque
stringData:
  apikey: {{ .Values.apiKey | default "" | quote }}